version: '2'

services:
  spark:
    image: docker.io/bitnami/spark:3.4
    container_name: spark
    hostname: spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
      - '8081:8081'
      - '7077:7077'
      - '4040:4040'
    volumes:
      #- "./container-data/sparkData:/opt/spark:rw"
      - "/var/CS4010/container-data/jupyterData/Spark:/home/jovyan/Spark/:rw"
  spark-worker:
    image: docker.io/bitnami/spark:3.4
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - "/var/CS4010/container-data/jupyterData/Spark:/home/jovyan/Spark/:rw"
    depends_on:
      - spark

  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    restart: unless-stopped
      #    environment:
      #      MONGO_INITDB_ROOT_USERNAME: root
      #      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - "./container-data/mongoData:/data/db:rw"


  jupyter:
    image: jupyter/pyspark-notebook
    container_name: jupyter
    hostname: jupyter
    restart: unless-stopped
    entrypoint: start-notebook.sh --NotebookApp.token=''
    ports:
      - "8888:8888"
    volumes:
      - "./container-data/jupyterData:/home/jovyan"
    
  grafana:
    image: grafana/grafana-oss:10.0.0
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    user: "0:0"
    ports:
      - "3000:3000"
    volumes:
      - "./container-data/grafanaData:/var/lib/grafana"
    environment:
      - "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=meln5674-mongodb-community"
      - "GF_INSTALL_PLUGINS=https://github.com/meln5674/grafana-mongodb-community-plugin/releases/download/v0.2.0%2Brc3/meln5674-mongodb-community.zip;meln5674-mongodb-community"

  #mongo-kafka-connect:
  #  build: .
  #  ports:
  #    - "8083:8083"
  #  depends_on:
  #    - kafka
