version: '2'

services:
  grafana:
    image: cs4010-grafana
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    user: "0:0"
    ports:
      - "3000:3000"
    environment:
      - "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=meln5674-mongodb-community"
      - "GF_INSTALL_PLUGINS=https://github.com/meln5674/grafana-mongodb-community-plugin/releases/download/v0.2.0%2Brc3/meln5674-mongodb-community.zip;meln5674-mongodb-community"